
#POST http://localhost:3000/signin 
#Content-Type: application/json

#{
#    "email": "test@thedailytech.net",
#    "password": "test1234"
#}

POST http://localhost:3000/signup
Content-Type: application/json

{
    "email": "test@thedailytech.net",
    "password": "test123",
    "fullname": "Test Daily Tech"
}