POST http://localhost/signin 
Content-Type: application/json

{
    "email": "test@thedailytech.net",
    "password": "test1234"
}

POST http://localhost/signup
Content-Type: application/json

{
    "email": "test@thedailytech.net",
    "password": "test1234",
    "fullname": "Test Daily Tech"
}